version: 0.2

phases:
  install:
    runtime-version:
      nodejs: 10
  build:
    commands:
      - npm run build

artifacts:
  files:
    - './front-end/**/*'
  discard-paths: no
  base-directory: build