# This is a basic workflow to help you get started with Actions

name: Backend to docker hub

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: docker login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD}}
          DOCKER_TAG: ${{ secrets.DOCKER_USERNAME}}/maestro/${date +%s}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: Build docker image
        run: docker build . --file Dockerfile.backend --tag $DOCKER_TAG

      - name: Push docker image 
        run: docker push $DOCKER_TAG
