# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - maestroreact

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: npm install, build, and test
      working-directory: front-end
      run: |
        npm install
        npm run build --if-present
        # npm run test --if-present

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'maestroreact'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_9500c4ed4f1141e6a0b57c72c12b6fe0 }}
        package: ./front-end
